name: tailer_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+1
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  introduction_screen: ^3.1.14
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  circular_bottom_navigation: ^2.4.0
  fluttertoast: ^8.2.8
  vector_math: ^2.1.0
  http: any
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  flutter_cube: 0.1.1
  image_card: ^0.0.4
  cached_network_image: any
  carousel_slider: ^5.0.0
  lottie: any
  google_sign_in: ^6.2.2
  flutter_easyloading: ^3.0.5
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.0
  googleapis_auth: any
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.1
  flutter_swipe_action_cell: ^3.1.5
  razorpay_flutter: ^1.3.7
  flutter_mjpeg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1  # Downgraded to avoid conflict

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo"  # Path to your app logo for launcher icons

flutter:
  uses-material-design: true

  assets:
    - assets/logo.json       
    - assets/heavy.glb      
    - assets/   
    - assets/gifs/
    - assets/lottie/
    - assets/images/
    - assets/images/Formal_Shirts/
    - assets/images/Traditional_Kameez/
    - assets/images/Sports_Shirts/
  

